### ISSUE TITLE
Installation Problem of Binding for TAPO P300

### ISSUE THREAD

**Issue by Wilhelm1Daniel** [wildcs/oh3_tapocontrol#8]
Hi

Try`d to install your 4.1 Snapshot... doesn't work.

I get the following failures in the log...

`
2023-11-24 11:27:22.763 [ERROR] [Events.Framework                    ] - FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.tapocontrol [27]
  Unresolved requirement: Import-Package: com.google.gson; version="[2.10.0,3.0.0)"
	at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.18.0.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847) ~[org.eclipse.osgi-3.18.0.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136) ~[org.eclipse.osgi-3.18.0.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840) ~[org.eclipse.osgi-3.18.0.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1783) ~[org.eclipse.osgi-3.18.0.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745) ~[org.eclipse.osgi-3.18.0.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667) ~[org.eclipse.osgi-3.18.0.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi-3.18.0.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi-3.18.0.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) ~[org.eclipse.osgi-3.18.0.jar:?]

2023-11-24 11:30:20.989 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.tapocontrol-4.1.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.tapocontrol [27]
  Unresolved requirement: Import-Package: com.google.gson; version="[2.10.0,3.0.0)"
	at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.18.0.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) ~[org.eclipse.osgi-3.18.0.jar:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) ~[?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) ~[?:?]
`

What I've done wrong?

Regards Daniel

**Comment by Wilhelm1Daniel** [comment]
Edit....

Using the 4.0.4 Snapshot works for me...

**Comment by Wilhelm1Daniel** [comment]
Another Hint...

You have to write the Protocol-Section in big letters when you use textual configuration... for example

`Bridge tapocontrol:bridge:myTapoBridge              "TAPO-Login"                 [ username="123456", password="123456" ] {
 Thing tapocontrol:P300:myTapoBridge:SZTisch         "SZ P300" @ "Schlafzimmer"   [ ipAddress="xxx.xxx.xxx.xxx", pollingInterval=30, protocol="KLAP" ]
}
`

Pherhaps you can add this in your Examples....


Greets Daniel

**Comment by wildcs** [comment]
@Wilhelm1Daniel 
For using the 4.1-snapshot you have to use the latest snapshot of oh. Minimun Build #3702
Thx for your hint with the ReadMe. Was an older version there. I'll correct it.
